### ISSUE TITLE
Readme instructions incomplete

### ISSUE THREAD

**Issue by mzryz** [uweseimet/atari_public#1]
Hi, I have been trying to setup the shutdown procedure and while following the instructions

```
In order to use RA_RTC und RA_SHUTD, with RaSCSI a host services device
(device type SCHS) with an arbitrary SCSI ID and a LUN < 0 has to be created.
This can be done with RaSCSI the web interface, the RaSCSI Control app or on
the command line, e.g.
>rascsi -ID 6 services

```
the command above just returns 'rascsi service is already running' - so I thought perhaps you mean rasctl? So I tried this command with rasctl but it removed all my previously attached disks/drives/devices so I don't think that works either.
I then checked in the web interface for a way to add this arbitrary device, but I do not see where I am supposed to do it, I am on the latest master branch. I am going to change to the develop branch because apparently 'attach peripheral device' was added, so perhaps this is where I do it.

**Comment by mzryz** [comment]
I think the command should be:

`rasctl -i 6 -c attach -t schs -n services`

**Comment by mzryz** [comment]
Ok after adding the services with the above command, running RA_SHUTD.prg, I am shown 'RaSCSI host services not found' Even though I have re-configured hd-driver and saved the config.

**Comment by mzryz** [comment]
OK fixed. After updating to the latest development release I could select in the web interface 'Rascsi host services' and mounted & saved my config, now every thing is working.

but still the command-line above does not work, so that should be updated in the readme. Cheers, will close.

**Comment by uweseimet** [comment]
@mzryz I'm sorry, I only saw your issue now, i.e. very late. (My notification settings  were wrong.)

The command line is fine. It assumes rascsi is not yet running. When it is already running and rasctl is used to add a service, the command has to be different, of course.
